name: Package Helm to GHCR
description: Package a helm chart and deploy to a Github Container Registry repository using OCI
branding:
  icon: hard-drive
  color: blue
inputs:
  gh-token:
    description: Github token to authenticate to Repo
    required: true
  gh-repo-owner:
    description: Github Repo Owner to deploy to
    default: "${{ github.repository_owner }}"
    required: false      
  chart-path:
    description: the directory path to the specified chart
    default: "."
    required: false
runs:
  using: "composite"
 
  steps:
    - name: install helm
      uses: Azure/setup-helm@v1

    - name: login to ghcr using helm
      shell: bash    
      run: |
        echo ${{ inputs.gh-token }} | helm registry login ${{ env.GCR_IMAGE }} --username ${{ inputs.gh-repo-owner }} --password-stdin
      env:
        HELM_EXPERIMENTAL_OCI: "1"
        GCR_IMAGE: ghcr.io/${{ inputs.gh-repo-owner }}

    - name: Install PyBump
      run: |
        python3 -m pip install pybump
      shell: bash
      
    - name: Helm Chart
      env:
        GCR_IMAGE: ghcr.io/${{ inputs.gh-repo-owner }}
        HELM_EXPERIMENTAL_OCI: "1"
      run : |
        version=$(pybump get --file ${{ inputs.chart-path }}/Chart.yaml)
        helm package \
        ${{ inputs.chart-path }} \
        --app-version $version \
        --version $version        
        ls *.tgz | xargs -i echo pushing {} to oci://$GCR_IMAGE && helm push {} oci://$GCR_IMAGE
      shell: bash
